// Published BTDB2 prices, as a bound on what the census is allowed to claim.
//
// GENERATED by tools/gen_price_table.py from data/btdb2_costs.json — edit those,
// not this. Upgrade costs were read off the INGAME COST field of the game's own
// tower menu at v4.13 on 2026-08-16, one upgrade at a time, so they are
// the client's numbers rather than a third party's transcription of them.
// 330/330 upgrades read in-game. 324 matched Blooncyclopedia exactly; 5 slots where the wiki carries a superseded duplicate were disambiguated; 1 (Monkeyopolis) is a formula the wiki records as a flat number. Base costs: 3 of 22 (Dart 200, Tack 280, Bomb 525) verified on the in-match shop panel, all matching the wiki; the other 19 remain wiki-sourced.
//
// Base tower costs are still wiki-sourced and UNVERIFIED — the tower menu prices
// upgrades but never the tower itself. They show on the in-match shop panel; read
// them there before treating minTowerCost/medianTowerCost as measured.
//
// This table does NOT price the opponent's towers, and cannot. Pricing stays
// with the learned sprite library (Sprites.swift), which reads exact figures off
// your own cash; the table has no way to say WHICH tower an appearance is. What
// it does give is the legal range, and that is enough to catch a whole class of
// bug for free — a price or a site count that no legal board could produce is
// wrong without needing to know what the right answer was.
//
// DELIBERATELY NOT DONE: snapping a learned or estimated price to the nearest
// legal value. The lattice of legal cumulative costs has 838 distinct values
// with a median gap of $15 below $3000, so 84.1% of ALL integers in $100–$3000
// sit within $10 of one. Agreement with the lattice is therefore evidence of
// nothing, and a "validator" built on it would report near-perfect confidence on
// noise. Measured 2026-08-16; do not reintroduce.
//
// Prices are LIST prices, and the floor is NOT. Read off the game's own text:
// Monkey Business (village path 3 tier 1) takes 5% off monkeys and upgrades of
// tier 3 or below in radius, and Monkey Commerce (tier 2) adds another 5% that
// "can stack with up to 2 other Villages" — 5 + 5x3 = 20% off at the limit. So
// the cheapest a site can genuinely cost is 80% of the cheapest tower, and a
// floor set at the sticker price would delete real observations of a
// village-discounted board. `minPaidCost` is the number to test against;
// `minTowerCost` is the sticker and is not a bound on anything.

import Foundation

enum PriceTable {
    /// Base cost of every tower in the game, cheapest first.
    static let baseCosts: [String: Int] = [
        "Glue Gunner": 100,
        "Dart Monkey": 200,
        "Tack Shooter": 280,
        "Sniper Monkey": 300,
        "Wizard Monkey": 300,
        "Boomerang Monkey": 325,
        "Monkey Sub": 325,
        "Ninja Monkey": 350,
        "Engineer Monkey": 400,
        "Druid": 425,
        "Ice Monkey": 450,
        "Monkey Buccaneer": 500,
        "Bomb Shooter": 525,
        "Alchemist": 550,
        "Spike Factory": 600,
        "Mortar Monkey": 700,
        "Monkey Ace": 750,
        "Dartling Gunner": 800,
        "Heli Pilot": 800,
        "Banana Farm": 1000,
        "Monkey Village": 1000,
        "Super Monkey": 2000,
    ]

    /// Cheapest tower at LIST price. Not a bound — see `minPaidCost`.
    static let minTowerCost = 100
    /// Deepest discount a purchase can carry: 20%, from stacked village
    /// upgrades. Quoted from the game's own upgrade text, not inferred.
    static let maxDiscount = 0.20
    /// Least real money a site can represent, discount included. THIS is the
    /// floor to test against: below it, no board could have produced the number.
    static let minPaidCost = 80
    /// Dearest tower before any upgrade.
    static let maxTowerCost = 2000
    /// Median base cost, used as the prior for a site whose appearance has never
    /// been priced. Flat, because tier is not observable — see TowerWatcher.
    static let medianTowerCost = 475
    /// Most that can legally be sunk into one site: 303100 is a fully
    /// upgraded Super Monkey with crosspath. Loose as bounds go — nothing in a
    /// real Battles 2 match approaches it — but it costs nothing to check.
    static let maxLegalCumulative = 303100

    /// Whether a cumulative cost is one a single site could legally hold. Bounds
    /// only; see the note above on why this is not a lattice test.
    static func isPlausibleCumulative(_ cost: Int) -> Bool {
        cost >= minPaidCost && cost <= maxLegalCumulative
    }

    /// Least the opponent can possibly have paid for `sites` towers — every one
    /// of them the cheapest in the game, every one of them fully discounted.
    /// Compared against what they could have earned, this falsifies a site COUNT
    /// without knowing what was built, which is the one thing the census cannot
    /// check about itself.
    static func floorSpend(sites: Int) -> Int { sites * minPaidCost }
}
