#!/usr/bin/env python3
"""Generate tracker/Sources/PriceTable.swift from data/btdb2_costs.json.

The JSON is the source of record; re-pull it from Blooncyclopedia's Cargo export
when a balance patch lands, then re-run this. Keeping the Swift generated rather
than hand-maintained means every constant in it traces back to a fetched row.

Usage:  python3 tools/gen_price_table.py
"""
import itertools
import json
import pathlib
import statistics

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "btdb2_costs.json"
OUT = ROOT / "tracker" / "Sources" / "PriceTable.swift"


def legal_cumulative_costs(towers, upgrades):
    """Every cumulative cost a single site can legally hold.

    Crosspath rule is BTD6's, which Battles 2 inherits: one path to any tier, a
    second to at most 2, the third untouched.
    """
    tiers = {}
    for u in upgrades:
        # Monkeyopolis prices as 20000 + 5000 per village absorbed, so it has no
        # constant to put in a lattice. Dropping it only understates Monkey
        # Village's own ceiling, which is far below the global max anyway.
        if u["cost"] is None:
            continue
        tiers.setdefault(u["tower"], {}).setdefault(u["path"], {})[u["tier"]] = u["cost"]

    out = set()
    for name, info in towers.items():
        if name not in tiers:
            continue
        for combo in itertools.product(range(6), repeat=3):
            ranked = sorted(combo, reverse=True)
            if ranked[1] > 2 or ranked[2] > 0:
                continue
            total, ok = info["cost"], True
            for path, tier in zip((1, 2, 3), combo):
                have = tiers[name].get(path, {})
                if any(t not in have for t in range(1, tier + 1)):
                    ok = False       # a formula-priced step; this combo has no fixed cost
                    break
                total += sum(have[t] for t in range(1, tier + 1))
            if ok:
                out.add(total)
    return sorted(out)


def main():
    data = json.loads(SRC.read_text())
    towers, upgrades = data["towers"], data["upgrades"]
    costs = sorted(info["cost"] for info in towers.values())
    lattice = legal_cumulative_costs(towers, upgrades)

    rows = "\n".join(
        f'        "{name}": {info["cost"]},'
        for name, info in sorted(towers.items(), key=lambda kv: kv[1]["cost"])
    )

    OUT.write_text(f'''// Published BTDB2 prices, as a bound on what the census is allowed to claim.
//
// GENERATED by tools/gen_price_table.py from data/btdb2_costs.json — edit those,
// not this. Upgrade costs were read off the INGAME COST field of the game's own
// tower menu at v{data["_game_version"]} on {data["_retrieved"]}, one upgrade at a time, so they are
// the client's numbers rather than a third party's transcription of them.
// {data["_verification"]}
//
// Base tower costs are still wiki-sourced and UNVERIFIED — the tower menu prices
// upgrades but never the tower itself. They show on the in-match shop panel; read
// them there before treating minTowerCost/medianTowerCost as measured.
//
// This table does NOT price the opponent's towers, and cannot. Pricing stays
// with the learned sprite library (Sprites.swift), which reads exact figures off
// your own cash; the table has no way to say WHICH tower an appearance is. What
// it does give is the legal range, and that is enough to catch a whole class of
// bug for free — a price or a site count that no legal board could produce is
// wrong without needing to know what the right answer was.
//
// DELIBERATELY NOT DONE: snapping a learned or estimated price to the nearest
// legal value. The lattice of legal cumulative costs has {len(lattice)} distinct values
// with a median gap of $15 below $3000, so 84.1% of ALL integers in $100–$3000
// sit within $10 of one. Agreement with the lattice is therefore evidence of
// nothing, and a "validator" built on it would report near-perfect confidence on
// noise. Measured 2026-08-16; do not reintroduce.
//
// Prices are LIST prices, and the floor is NOT. Read off the game's own text:
// Monkey Business (village path 3 tier 1) takes 5% off monkeys and upgrades of
// tier 3 or below in radius, and Monkey Commerce (tier 2) adds another 5% that
// "can stack with up to 2 other Villages" — 5 + 5x3 = 20% off at the limit. So
// the cheapest a site can genuinely cost is 80% of the cheapest tower, and a
// floor set at the sticker price would delete real observations of a
// village-discounted board. `minPaidCost` is the number to test against;
// `minTowerCost` is the sticker and is not a bound on anything.

import Foundation

enum PriceTable {{
    /// Base cost of every tower in the game, cheapest first.
    static let baseCosts: [String: Int] = [
{rows}
    ]

    /// Cheapest tower at LIST price. Not a bound — see `minPaidCost`.
    static let minTowerCost = {costs[0]}
    /// Deepest discount a purchase can carry: 20%, from stacked village
    /// upgrades. Quoted from the game's own upgrade text, not inferred.
    static let maxDiscount = 0.20
    /// Least real money a site can represent, discount included. THIS is the
    /// floor to test against: below it, no board could have produced the number.
    static let minPaidCost = {int(costs[0] * 0.8)}
    /// Dearest tower before any upgrade.
    static let maxTowerCost = {costs[-1]}
    /// Median base cost, used as the prior for a site whose appearance has never
    /// been priced. Flat, because tier is not observable — see TowerWatcher.
    static let medianTowerCost = {int(statistics.median(costs))}
    /// Most that can legally be sunk into one site: {max(lattice)} is a fully
    /// upgraded Super Monkey with crosspath. Loose as bounds go — nothing in a
    /// real Battles 2 match approaches it — but it costs nothing to check.
    static let maxLegalCumulative = {max(lattice)}

    /// Whether a cumulative cost is one a single site could legally hold. Bounds
    /// only; see the note above on why this is not a lattice test.
    static func isPlausibleCumulative(_ cost: Int) -> Bool {{
        cost >= minPaidCost && cost <= maxLegalCumulative
    }}

    /// Least the opponent can possibly have paid for `sites` towers — every one
    /// of them the cheapest in the game, every one of them fully discounted.
    /// Compared against what they could have earned, this falsifies a site COUNT
    /// without knowing what was built, which is the one thing the census cannot
    /// check about itself.
    static func floorSpend(sites: Int) -> Int {{ sites * minPaidCost }}
}}
''')
    print(f"wrote {OUT.relative_to(ROOT)}: {len(towers)} towers, "
          f"{len(upgrades)} upgrades, lattice {len(lattice)} values, "
          f"floor ${costs[0]} median ${int(statistics.median(costs))} max ${max(lattice)}")


if __name__ == "__main__":
    main()
